### ISSUE TITLE
Default multi-choice Filter doesn't  work in grids

### ISSUE THREAD

**Issue by gotgelf** [orocrm/platform#104]
if we define multi choice filter in grid configuration, for example:

```
            test:
                type: choice
                data_name: test
                options:
                    field_options:
                        multiple: true              
```

and then will try to set default value:

```
            default:
               test: { value: 'testvalue' }
```

it will not work.

option multiple is not true, then everything works.
