### ISSUE TITLE
Unrecognized options "rules" under "fos_rest.format_listener"

### ISSUE THREAD

**Issue by mitecube** [orocrm/platform#212]
When I install the Oro Platform, I receive the following error:

```
PHP Fatal error:  Uncaught exception 
'Symfony\Component\Config\Definition\Exception\InvalidConfigurationException' with message 
'Unrecognized options "rules" under "fos_rest.format_listener"' in 
/Users/fdellutri/Documents/educacloud/vendor/symfony/symfony/src/Symfony/Component/Config/Definition/ArrayNode.php:316
```

The config.yml is left untouched:

```
fos_rest:
    body_listener:
            decoders:
                json: fos_rest.decoder.json
    view:
        failed_validation: HTTP_BAD_REQUEST
        default_engine: php
        formats:
            json: true
            xml: false
    format_listener:
        rules:
            - { path: '^/api/rest', priorities: [ json ], fallback_format: json, prefer_extension: false }
            - { path: '^/api/soap', stop: true }
            - { path: '^/', stop: true }
    routing_loader:
        default_format: json
```
