### ISSUE TITLE
Default filter for datagrids can't be cleared

### ISSUE THREAD

**Issue by cawolf** [orocrm/platform#228]
Hi,

we are using datagrids extensively and want to set a default value for a datetime filter like this:
```yaml
datagrid:
    my-data-grid:
        filters:
            default:
                my-datetime-field:
                    value:
                        start: '{{2}} - 90'
                        end: '{{2}}'
```

This has the desired effect, the grid is correctly filtered. We can also change the filter values and everything works fine.

However, when we **clear** the filter (by clicking the "X"), the filter element shows "All", but the datagrid contains only elements which match the default filter. This is very confusing for our users, as "All" does mean "Default" for this datetime field.

Could you 
- either change the label from "All" to "Default" (or even better: the initial default label, in this case "between today - 90 and today")
- or remove the "X" and thus removing the possibility to clear the filter
- or force the backend to respect the cleared filter and override the default value in this case?

Every option would help our users to use the datagrid correctly and not be confused anymore. Thank you in advance,

best regards,
Christian
