### ISSUE TITLE
Additional group by statements change datagrid results

### ISSUE THREAD

**Issue by LRotherfield** [orocrm/platform#241]
We have the following datagrid config:
```
datagrid:
    dashboard-top-search-terms:
        source:
            type: orm
            query:
                select:
                    - t.term
                    - t.lastNumResults
                    - COUNT(h.id) AS hits
                    - h.createdAt as lastSearched
                from:
                    - { table: DefactoSearchBundle:SearchTerm, alias: t }
                join:
                    inner:
                        - { join: t.hits, alias h }
                groupBy: t.term
                orderBy:
                    - { column: hits, dir: DESC }
                    - { column: t.lastNumResults, dir: DESC }
        columns:
            term:
                label: Term
            hits:
                label: Hits
            lastNumResults:
                label: Results
```
Before the release of platform version 1.6 the returned query was:
`SELECT d0_.term AS term0, d0_.last_num_results AS last_num_results1, COUNT(d1_.id) AS sclr2, d1_.created_at AS created_at3 FROM df_search_term d0_ INNER JOIN df_search_term_hit d1_ ON d0_.id = d1_.search_term_id GROUP BY d0_.term ORDER BY sclr2 DESC, d0_.last_num_results DESC LIMIT 5 OFFSET 0`
Here we get the correct group by statement of: `GROUP BY d0_.term`
This returns the correct results showing the number of hits per search term.

After upgrading to 1.6, the query now looks like: `SELECT d0_.term AS term0, d0_.last_num_results AS last_num_results1, COUNT(d1_.id) AS sclr2, d1_.created_at AS created_at3 FROM df_search_term d0_ INNER JOIN df_search_term_hit d1_ ON d0_.id = d1_.search_term_id GROUP BY d0_.term, d0_.last_num_results, created_at3 ORDER BY sclr2 DESC, d0_.last_num_results DESC LIMIT 5 OFFSET 0`
Notice that the group by has changed to `GROUP BY d0_.term, d0_.last_num_results, created_at3`
This means the incorrect data is returned because the hits are grouped by created_at3 which means the query always returns rows with 1 hit.

The additional group by fields are added due to the changes in this commit: https://github.com/orocrm/platform/commit/08b8129a34ff5ed88931ff09e8e11c4f38d0d522 Which is later modified by https://github.com/orocrm/platform/commit/a57b494a36e495da9a69ffcad21e9acbf4a9e07f

Is adding the non aggregate selected data required? 

I know that the datagrid config can be changed to fix this and that is what I have done, I just am not sure why we cannot select the data that we want:

```
datagrid:
    dashboard-top-search-terms:
        source:
            type: orm
            query:
                select:
                    - t
                    - COUNT(h.id) AS hits
                from:
                    - { table: DefactoSearchBundle:SearchTerm, alias: t }
                join:
                    inner:
                        - { join: t.hits, alias h }
                groupBy: t.term
                orderBy:
                    - { column: hits, dir: DESC }
                    - { column: t.lastNumResults, dir: DESC }
```

**Comment by vsoroka** [comment]
This modification was made to make sure that the grid creates correct query for all supported databases. It means that all non aggregated columns must be added to GROUP BY statement.
In your case you can just change the datagrid config to:
```yaml
                select:
                    - t.term
                    - MAX(t.lastNumResults) AS lastNumResults
                    - COUNT(h.id) AS hits
                    - MAX(h.createdAt) AS lastSearched
                from:
                    - { table: DefactoSearchBundle:SearchTerm, alias: t }
                join:
                    inner:
                        - { join: t.hits, alias h }
                groupBy: t.term
                orderBy:
                    - { column: hits, dir: DESC }
                    - { column: lastNumResults, dir: DESC }
```
