### ISSUE TITLE
Workflow condition check problem

### ISSUE THREAD

**Issue by sbani** [orocrm/platform#251]
Hey.

found a problem with the conditions (transition definition):

I loaded the workflow and  wanted to go to the next step. No error during workflow:definitions:load.

The error:
`Fatal error: Call to a member function isAllowed() on null in /var/www/vhosts/orocrm/vendor/oro/platform/src/Oro/Bundle/WorkflowBundle/Model/Condition/Configurable.php on line 49`

The line: `return $this->condition->isAllowed($context, $errors);`

The problem:
```yaml
            develop_definition:
                conditions:
                    - @greater_or_equal:
                        message: 'Budget amout must be greater or equal to 0'
                        parameters: [$budget_amount, 0]
```

The `-` is the problem.

I would add an exception here:
```php
    public function isAllowed($context, Collection $errors = null)
    {
        if (!$this->condition) {
            $this->condition = $this->assembler->assemble($this->configuration);
        }

         if (!$this->condition) {
            throw new ConditionException('Error during condition loading');
        }
        return $this->condition->isAllowed($context, $errors);
    }
```

And then extend the check. Don't know where the checks happen.

I will try to fix it if I have enough time.
