### ISSUE TITLE
OroConfigBundle: doesn't save new settings

### ISSUE THREAD

**Issue by alexkuk** [orocrm/platform#317]
Hello!

I'm working on the Akeneo integration, and adding one settings field, that should be handled by OroConfigBundle.
A field is displayed on a configuration page, but can't be saved - it says "Configuration saved" but after reloading a page the field is still empty, also no value written in DB.
Here's my system_configuration.yml example:
```yml
oro_system_configuration:
    groups:
        catalog:
            title: 'Catalog'
            icon:  'icon-folder-open'
        catalog_general_setup:
            title: 'General setup'
        products:
            title: 'Products'
        products_settings:
            title: 'Products settings'

    fields:
        mybundle.my_value:
            type: text
            priority: 10
            options:
                label: 'My Value'

    tree:
        system_configuration:
            catalog:
                children:
                    catalog_general_setup:
                        children:
                            products:
                                children:
                                    products_settings:
                                        children:
                                            - mybundle.my_value
```

I found this code prevents it from being saved:
\Oro\Bundle\ConfigBundle\Config\ConfigManager::getChanged():
```php
// save only if setting exists and there's no default checkbox checked
            if (!is_null($currentValue) && empty($value['use_parent_scope_value'])) {
                $updated[$key] = $value;
            }
```
As it's a new field, $currentValue is null in my case and getChanged() returns an empty array, and now values are saved.

Will you fix it? Or do I miss something?
