### ISSUE TITLE
Default value datagrid doesn't work

### ISSUE THREAD

**Issue by souhirBen** [orocrm/platform#404]
Hi,

I'm trying to use a default value in my datagrid but it doesn't work. It works only after I click in options -> discard changes (the link next to the Title).

```yml
datagrid:
    example-grid:
        filters:
            default:
                datetime-field:
                    value:
                        start: '2015-02-01'
                        end: '{{2}}' 
                     type: %oro_filter.form.type.filter.datetime_range.class%::TYPE_BETWEEN

```
