### ISSUE TITLE
Allow HTML image links in email?

### ISSUE THREAD

**Issue by codesman** [orocrm/platform#415]
Hello ORO Team!

What needs to be done to enable HTML linked images in email?

Using base64 encoded images in emails is causing a heavy database bloat issue for us and I assume it's a problem for others as well.  We have only been embedding images for the last month or so and already the oro_email_attachment_content table is close to 1GB, with the majority of that being the same encoded header image being replicated over and over. It is causing the same data bloat on our email server.

Being able to link these images instead of having to encode them would eliminate this issue but it appears a decision has been made to not allow them because although linked images work in the composer, they get stripped out on send. Is this a bug or expected behavior?  Why have HTML images been disabled(or not implemented)?

I'm willing to work on this if you can give me some direction as to what needs to be done.

Tom

**Comment by mccar** [comment]
Hello
HTML images feature is not implemented. But stripped link images on email send is a bug.
If you would like to implement this feature you can look at Oro\Bundle\EmailBundle\Mailer\Processor.php -> processEmbeddedImages(). This method prepares message to send and cuts all img tags without checking on embedded type.

**Comment by yurio** [comment]
Hi @codesman. 
Here is a patch https://gist.github.com/yurio/e59752ae4802dc1efe9b that turns on standard image plugin that will allow to add images by link at the text editor and fix cutting <img> tag. It needs to be finished, but main part of the work was done. You could use it to prepare the fix you need. We will appreciate your contribution to the platform. Thanks in advance!

**Comment by codesman** [comment]
Awesome! Thanks @yurio & @mccar, I'll spin up a dev environment and see if my kungfu is strong enough to finish it!

**Comment by codesman** [comment]
Hi there @yurio & @mccar ,

It appears that the issue of a linked html image getting "broken" on send has been fixed in either 1.9.2 or 1.9.3.  I just tested a clean install of platform-application 1.9.3 and sent an email that had an image link and it went just fine, so the "hack" in Mailer/Processor is not necessary.

Do you know what was changed that fixed this?

Thanks, Tom

**Comment by codesman** [comment]
So, now that the html linked image is fixed in the platform core, all I need to do in my app is remove the `bdesk_photo` icon from the toolbar so users can't use it.

I can accomplish this by editing the `$toolbars` property directly in `\Oro\Bundle\FormBundle\Form\Type\OroRichTextType.php`, but I can't get it to work by extending the service class from my bundle.

My Bundle has a form_type.yml that I am importing in app/config/config.yml that has this in it:
```YAML
parameters:
    oro_form.type.rich_text.class: Acme\Bundle\FormBundle\Form\Type\AcmeRichTextType

services:
    oro_form.type.rich_text:
            class: %oro_form.type.rich_text.class%
            arguments:
                - @oro_config.user
                - @oro_form.provider.html_tag_provider
                - %kernel.cache_dir%
            calls:
                - [setAssetHelper, [@assets.packages]]
            tags:
                - { name: form.type, alias: oro_rich_text }
```

and then I have `Acme\Bundle\FormBundle\Form\Type\AcmeRichTextType.php` which extends `OroRichTextType` and it looks like this:
```PHP
class AcmeRichTextType extends OroRichTextType
{
	/**
	 * @url http://www.tinymce.com/wiki.php/Configuration:toolbar
	 * @var array
	 */
	public static $toolbars = [
		self::TOOLBAR_SMALL   => ['undo redo | bold italic underline | bullist numlist link'],
		self::TOOLBAR_DEFAULT => [
			'undo redo | bold italic underline | forecolor backcolor | bullist numlist | link | code'
		],
		self::TOOLBAR_LARGE   => [
			'undo redo | bold italic underline | forecolor backcolor | bullist numlist | link | code'
		],
	];

	/**
	 * @var array
	 */
	public static $defaultPlugins = ['textcolor', 'code', 'link'];
}
```

When I do `php app/console container:debug  oro_form.type.rich_text`, I get this:
```PHP
Service Id       oro_form.type.rich_text
Class            Acme\Bundle\FormBundle\Form\Type\AcmeRichTextType
````

So it appears that the service is using my extended class, but the icon is still in the toolbar even though I have extended the class and overwritten the `$toolbars` property to remove the `bdesk_photo` icon.  Can you tell me what I am doing wrong?  What do I need to do to override this property from my bundle so I don't have to hack the platform?

Thanks again!
Tom
