### ISSUE TITLE
Inline editing behaviour looks not working. All columns have enabled inline editing

### ISSUE THREAD

**Issue by stepansib** [orocrm/platform#463]
I have following config for my datagrid:

```    
crm-invoice-items-by-invoice-editable-view-grid:
        ...
        inline_editing:
            enable: true
            entity_name: %crm.invoice_item.entity.class%
            behaviour: enable_selected
        save_api_accessor:
            http_method: PATCH
            route: crm_invoice_item_update
        ...
        columns:
            name:
                inline_editing:
                    enable: true
        ...
```

As we can see i allow inline editing only to column "name"
The inline editing behaviour is `enable_selected`. I expect that all columns will be not editable in grid but only the "name" column. Instead of this, all the columns are editable.

Oro Platform 1.9.0
