### ISSUE TITLE
LinkProperty don't work if label is null ( left join on foreign table )

### ISSUE THREAD

**Issue by sebheitzmann** [orocrm/platform#469]
I use the link property in a datagrid to make a link to a foreign record. It works good if the foreign key is not null but when the foreign key is null the route cannot be generated and should not.

```
    incident-grid:
        source:
           #acl_resource: crm.chargement.view
            type: orm
            query:
                select:
                    - i.id
                    - i.cle
                    - d.id as d_id
                    - d.cle as dossierLibelle
                from:
                    - { table: 'Lle\Hemmerlin\CrmBundle\Entity\Incident', alias: i }
                join:
                    left:
                        - { join: i.dossier, alias: d }
        columns:
            cle:
                label: 'N° Incident'
            d_id:
                label: 'Dossier'
                type: link
                route: crm_dossier_view
                params:
                    id: "d_id"
```

I think that the getRawValue for LinkProperty should return "" if the label is empty;

```

public function getRawValue(ResultRecordInterface $record)
    {
        $label = null;
        try {
            $label = $record->getValue($this->getOr(self::DATA_NAME_KEY) ?: $this->get(self::NAME_KEY));
        } catch (\LogicException $e) {
        }

        ///// ADD THIS
        if (!$label) return "";
        ///// END ADD

        return $this->twig
            ->loadTemplate(self::TEMPLATE)
            ->render(
                [
                    'url'   => parent::getRawValue($record),
                    'label' => $label
                ]
            );
    }
```
That was done in the suggestion from the issue #149

But maybe I missed something in the usage.
