### ISSUE TITLE
Dashboard: "Same Grid" on the same site is only rendering once

### ISSUE THREAD

**Issue by sbani** [orocrm/platform#488]
Hi,

I have built two Dashboards with the same Grid as content, but with different params.
## Problem

The dashboard shows two times the content of `state: state1` (the first dashboard).
## Guessing the solution

I haven't found the problem itself, because the requests and the response content of the subrequests look good. 
I think the problem is the datagrid js renderer, because it seems like it's somehow caching the rendered grid content by grid name and ignores the two different backend responses.
## Code

datagrid.yml:

``` yml
    dashboard-user-foo-state:
        extends: dashboard-user-foo
        source:
            query:
                where:
                    and:
                        - cp.state = :state
            bind_parameters:
                state: state
```

dashboard.yml:

``` yml
        my_foo_state1:
            label:       app.foo.dashboard.my_foo_state1.title
            route:       oro_dashboard_widget
            route_parameters: { bundle: AppBundle, name: myFooState, state: 'state1' }
            acl:         app_foo_view
            description: app.foo.dashboard.my_foo.description

        my_foo_state2:
            label:       app.foo.dashboard.my_foo_state2.title
            route:       oro_dashboard_widget
            route_parameters: { bundle: AppBundle, name: myFooState, state: 'state2' }
            acl:         app_foo_view
            description: app.foo.dashboard.my_foo.description
```

AppBundle:Dashboard:myFooState.html.twig:

``` html
{% extends 'OroDashboardBundle:Dashboard:widget.html.twig' %}
{% import 'OroDataGridBundle::macros.html.twig' as dataGrid %}

{% set gridName = 'dashboard-user-foo-state' %}

{% set state = app.request.query.get('state') %}

{% block content %}
    {{ dataGrid.renderGrid(gridName, {'userId': app.user.id, 'state': state}) }}
{% endblock %}

{% block actions %}
    {% set actions = [{
        'url': path('app_foo_index'),
        'type': 'link',
        'label': ('app.foo.dashboard.my_foo_'~ state ~'.view_all')|trans
    }] %}

    {{ parent() }}
{% endblock %}
```

You can test it with every datagrid and an extra param.
My temporary solution are two datagrids which is stupid, but works
