### ISSUE TITLE
"The exclusion_policy must be all" when creating entity via API

### ISSUE THREAD

**Issue by adamlundrigan** [orocrm/platform#490]
I'm running `dev-master` so I can work with the new parts of ApiBundle.  Retrieving an instance of my custom entity works very well but when I try to create an instance via POST:

```
POST /api/registrationcourseregistrations HTTP/1.1
Authorization: WSSE profile="UsernameToken"
X-WSSE: UsernameToken Username="xxxxxx", PasswordDigest="xxxxxx", Nonce="xxxxxx", Created="xxxxxx"
Content-Type: application/x-www-form-urlencoded
Cache-Control: no-cache

courseOffering=2&courseOfferingGroup=3&employee=293&employeeProfile=293&status=P
```

 I get a 500 with this response:

```json
[
  {
    "title": "runtime exception",
    "detail": "The \"exclusion_policy\" must be \"all\"."
  }
]
```

The Registration entity I'm trying to create there has 4x ManyToOne associations -- Offering, Group, Employee and Profile.

<details>
<summary>This is how the entity is configured in Resources/config/oro/api.yml</summary>
```yaml
oro_api:
    entities:

      Application\Bundle\RegistrationBundle\Entity\CourseRegistration:
        fields:
          courseOffering:
            fields:
             id: ~
             status: ~
             course:
               fields:
                 id: ~
                 title: ~
                 titleSlug: ~
                 status: ~
             schedule:
               fields:
                 id: ~
                 start: ~
                 end: ~
          courseOfferingGroup:
            fields:
             id: ~
             nickname: ~
             status: ~
             minSeats: ~
             maxSeats: ~
             registrationDeadline: ~
             withdrawalDeadline: ~
             cancellationDeadline: ~
          employee:
            fields:
              id: ~
              username: ~
              emailAddresses:
                fields:
                  id: ~
                  email: ~
                  primary: ~
          employeeProfile:
            fields:
              id: ~
              employeeId: ~
              firstName: ~
              lastName: ~
              businessUnit:
                fields:
                  id: ~
                  name: ~
              address:
                fields:
                  id: ~
                  street: ~
                  street2: ~
                  city: ~
                  region: ~
                  postalCode: ~
                  country: ~
              positionTitle: ~
              positionFunction: ~
              unionCode: ~
              classification: ~
              pcn: ~
              status: ~
              isCurrent: ~
              createdDate: ~
              lastValidatedDate: ~
              replacedDate: ~
        filters:
          fields:
            id:
              exclude: false
              allow_array: true
            courseOffering:
              exclude: false
              allow_array: true
            courseOfferingGroup:
              exclude: false
              allow_array: true
            employee:
              exclude: false
              allow_array: true
            status:
              exclude: false
              allow_array: true
        actions:
          update: false
          delete: false
          delete_list: false
```
</details>

<details>
<summary>...and this is what the response to a `GET /api/registrationcourseregistrations/:id` looks like.</summary>
```
{
  "data": {
    "type": "registrationcourseregistrations",
    "id": "21",
    "relationships": {
      "courseOffering": {
        "data": {
          "type": "courseofferings",
          "id": "2"
        }
      },
      "courseOfferingGroup": {
        "data": {
          "type": "inclassgroups",
          "id": "3"
        }
      },
      "employee": {
        "data": {
          "type": "employees",
          "id": "293"
        }
      },
      "employeeProfile": {
        "data": {
          "type": "employeeprofiles",
          "id": "293"
        }
      }
    },
    "attributes": {
      "status": "P",
      "createdAt": "2016-07-05T15:47:26Z",
      "updatedAt": "2016-07-05T15:47:26Z"
    }
  },
  "included": [
    {
      "type": "courses",
      "id": "2",
      "attributes": {
        "title": "Another Test Course",
        "titleSlug": "another-test-course",
        "description": "Testing 12345",
        "status": "A",
        "createdAt": {
          "date": "2016-05-24 16:09:27.000000",
          "timezone_type": 3,
          "timezone": "UTC"
        },
        "updatedAt": {
          "date": "2016-07-01 23:55:05.000000",
          "timezone_type": 3,
          "timezone": "UTC"
        }
      }
    },
    {
      "type": "courseofferings",
      "id": "2",
      "attributes": {
        "status": "A"
      },
      "relationships": {
        "course": {
          "data": {
            "type": "courses",
            "id": "2"
          }
        },
        "schedule": {
          "data": []
        }
      }
    },
    {
      "type": "inclassgroups",
      "id": "3",
      "attributes": {
        "nickname": "Testing Group",
        "status": "A",
        "minSeats": 10,
        "maxSeats": 50,
        "registrationDeadline": null,
        "withdrawalDeadline": null,
        "cancellationDeadline": null
      }
    },
    {
      "type": "employeeemailaddresses",
      "id": "293",
      "attributes": {
        "email": "adam@lundrigan.ca",
        "primary": true
      }
    },
    {
      "type": "employees",
      "id": "293",
      "attributes": {
        "username": "XXXXXX"
      },
      "relationships": {
        "emailAddresses": {
          "data": [
            {
              "type": "employeeemailaddresses",
              "id": "293"
            }
          ]
        }
      }
    },
    {
      "type": "employeeprofiles",
      "id": "293",
      "attributes": {
        "firstName": "Eldred",
        "lastName": "Leuschke",
        "positionTitle": "",
        "status": "A",
        "isCurrent": true,
        "createdDate": {
          "date": "2016-05-12 02:56:35.000000",
          "timezone_type": 3,
          "timezone": "UTC"
        },
        "lastValidatedDate": {
          "date": "2016-05-15 13:45:37.000000",
          "timezone_type": 3,
          "timezone": "UTC"
        },
        "replacedDate": null
      },
      "relationships": {
        "businessUnit": {
          "data": {
            "type": "businessunits",
            "id": "296"
          }
        },
        "address": {
          "data": null
        }
      }
    }
  ]
}
```
</details>

...but when I create a new instance of this entity via the API the record is created successfully but the API throws back that `The "exclusion_policy" must be "all".` exception.  The source of that exception is [`ObjectNormalizer::normalizeObjectByConfig`](https://github.com/orocrm/platform/blob/163d293458df585c7a9508ff78a5f391f1ea55de/src/Oro/Bundle/ApiBundle/Normalizer/ObjectNormalizer.php#L129-L137)  Since the `get`/`get_list` can serialize the entity properly I don't see why `create` throws an exception here.  If I comment out that block of code in ObjectNormalizer:

```php
        if (!$config->isExcludeAll()) {
            throw new \RuntimeException(
                sprintf(
                    'The "%s" must be "%s".',
                    EntityDefinitionConfig::EXCLUSION_POLICY,
                    EntityDefinitionConfig::EXCLUSION_POLICY_ALL
                )
            );
        }
```

The POST request will now return a 201 response with the serialized entity. 

I hacked that block of code an additional line that printed the class name of the entity causing the problem and it is "Course", which is OneToMany-associated with CourseOffering.  I tried 

 - Setting `exclusion_policy: all` for that entity in `api.yml`.
 - Adding the `JMS\ExclusionPolicy("all")` annotation to the entity class.

Manually cleared the cache after both actions but neither caused the exception to stop.

Is it a bug, or do I just have something configured incorrectly?

**Comment by vsoroka** [comment]
Hi @adamlundrigan,

- In whole your configuration is correct. But in term of JSON.API it is not good idea to return details of related entities if a client does not request it directly. Please look at [Inclusion of Related Resources](http://jsonapi.org/format/#fetching-includes) and [Sparse Fieldsets](http://jsonapi.org/format/#fetching-sparse-fieldsets). So, you can keep your api.yml file very simple:
```yaml
oro_api:
    entities:
      Application\Bundle\RegistrationBundle\Entity\CourseRegistration: ~
```
The `include` and `fields` filters will be added automatically and they can be used if someone will need details about related entities.

- Currently POST and PATCH methods can work only identifiers of related entities. We plan to improve this and in the future it will be possible to create/update primary entity and related entities in single API call.

- JMS Serializer, as well as Symfony Serializer, is not used in ApiBundle at all. It is because the serialization should be based on API configs.

- Regarding the error: it seems that it is a bug. I've created an issue and we will prepare a fix. But most of all the fix will be ready in autumn because now we have a lot of work due to the release of 1.10. Please let us know if it is a blocker for you and we will try to prepare the fix ASAP.
