### ISSUE TITLE
Domain Object exception when trying to put oro code into "/admin" prefix

### ISSUE THREAD

**Issue by LRotherfield** [orocrm/platform#53]
I am trying to set a prefix "/admin" on all oro routes.  To do this I added

``` yaml
#navigation.yml
oro_default:
    pattern:  /admin
    defaults:
        _controller: OroDashboardBundle:Dashboard:index

oro_auto_routing:
    prefix:   /admin
    resource: .
    type:     oro_auto
```

I also added the prefix to login areas of the security.yml and I have the following access control:

``` yaml
        install:
            pattern:                        ^/admin/installer
#...
        wsse_secured:
            pattern:                        ^/admin/api/(rest|soap).*
#...
        login:
            pattern:                        ^/admin/user/(login|reset-request|send-email|check-email)$
#...
        reset_password:
            pattern:                        ^/admin/user/reset/*
#...
    access_control:
        - { path: ^/admin/user/(login|reset-request|send-email|check-email), role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/user/reset/*, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/, role: ROLE_ADMINISTRATOR }
        - { path: ^/api/rest/(latest|v1)/pinbars, role: ROLE_USER }
```

I am getting the following exception:

> $domainObject must either implement the DomainObjectInterface, or have a method named "getId".
> in /vendor/oro/platform/src/Oro/Bundle/SecurityBundle/Acl/Domain/ObjectIdAccessor.php at line 27 
> at ObjectIdAccessor ->getId (object(Request)) 
> 
> in /vendor/oro/platform/src/Oro/Bundle/SecurityBundle/Acl/Extension/AclExtensionSelector.php at line 84 
> at AclExtensionSelector ->select (object(Request)) 
> 
> in /vendor/oro/platform/src/Oro/Bundle/SecurityBundle/Acl/Voter/AclVoter.php at line 85 
> at AclVoter ->vote (object(AnonymousToken), object(Request), array('IS_AUTHENTICATED_ANONYMOUSLY')) 
> 
> in kernel.root_dir/cache/dev/classes.php at line 4606 
> at AccessDecisionManager ->decideUnanimous (object(AnonymousToken), array('IS_AUTHENTICATED_ANONYMOUSLY'), object(Request)) 
> 
> in kernel.root_dir/cache/dev/classes.php at line 4531 
> at AccessDecisionManager ->decide (object(AnonymousToken), array('IS_AUTHENTICATED_ANONYMOUSLY'), object(Request)) 
> 
> in /vendor/symfony/symfony/src/Symfony/Component/Security/Http/Firewall/AccessListener.php at line 69
