### ISSUE TITLE
AssignValueAction don't when called by another post_actions worflow

### ISSUE THREAD

**Issue by geoffroycochard** [orocrm/platform#564]
Hie,

My use case : 
i got 2 workflows in different entities. Entity_1_Workflow_1 and Entity_2_Workflow_2.

```
#Entity_1_Workflow_1
workflow:
  ...
  transition_definitions:
    ...
    is_definition:
      - @assign_value: [$status, 4]
      - @custom_action_1: ~
```
```
#Entity_2_Workflow_2
workflow:
  ...
  transition_definitions:
    ...
    is_definition:
      - @custom_action_2: ~
```

In my `@custom_action_2` when i call `$workflowManager->transit(entity1WorkflowItem, to_step)` (is_definition is transition_definition in "to_step" transition),` @custom_action_1` is executed but `@assign_value: [$status, 4]` not saved entity update. @assign_value is correctly execute but i trace doctrine logs i find only one request `UPDATE entity_1` who update `workflow_step_id` but no trace of `UPDATE entity_1` who update `status`.

Otherwise when i call Entity_1_Workflow_1.is_definition all is executed right (`@custom_action_1`& `@assign_value: [$status, 4]`).

Have you get this case already ?

Thanks,
Geoffroy

**Comment by mbessolov** [comment]
Thank you Geoffroy, we will try to reproduce.

**Comment by manowark** [comment]
Hi, @geoffroycochard.

I tried to reproduce your case. But I couldn't.

There is my test configuration of workflow.
```
workflows:
    b2b_order_workflow1:
        label: Order
        entity: OroB2B\Bundle\OrderBundle\Entity\Order
        entity_attribute: test #not required parameter (it equals 'entity' by default)
        start_step: step1
        steps_display_ordered: true

        attributes:
            identifier:
                type: int
                label: oro.acme.identifier.label

        steps:
            step1:
                label: step1
                order: 10
                allowed_transitions:
                    - to_step2
            step2:
                label: step2
                order: 20
        transitions:
            to_step2:
                label: to step 2
                step_to: step2
                transition_definition: to_step2_definition

        transition_definitions:
            to_step2_definition:
                post_actions:
                    - '@assign_value': [$identifier, 4]
                    - '@assign_value': [$.test.identifier, 5]
```

As you see, I have 2 assignment. Only second assignment will change property of my entity.

First assignment set value of attribute `identifier` in `WorkflowData` of `WorkflowItem` attached to your entity. And that attribute stored in the same level that attribute `test` with entity `Oro\Bundle\AcmeBundle\Entity\Test`.

So, after transition in `data` field of `WorkflowItem` I see `"{"identifier":4}"` and in `identifier` field of my entity I see `5`.

@geoffroycochard, please let me know if I incorrect understand your problem or if I help you with solution.
