### ISSUE TITLE
Typo in API howto manual

### ISSUE THREAD

**Issue by stepansib** [orocrm/platform#621]
We have an example [Turn on API for entity](https://github.com/orocrm/platform/blob/master/src/Oro/Bundle/ApiBundle/Resources/doc/how_to.md#turn-on-api-for-entity) with the following example:
```yml
api:
    entities:
        Acme\Bundle\ProductBundle\Product: ~
```

i think you have to change `api` to `oro_api`
