### ISSUE TITLE
JWT Authentification for ORO Api 

### ISSUE THREAD

**Issue by Kshapova** [orocrm/platform#635]
Hi

I need to replace WSSE API Authentification and add JWT Authentification (with IdToken). 

I created a new bundle and added a new JWT firewall 
````
        api:
            pattern: ^/api
            provider: jwt
            stateless: true
            anonymous: false
            guard:
                authenticators:
                    - app.jwt_token_authenticator
                entry_point: app.jwt_token_authenticator
            context: main
````
It works fine with the API. 
But API in ORO js files always need WSSE Authetification. (For exemple in TagBundle when you add a Tag to the Entity: API POST /api/rest/{version}/tags/{entity}/{entityId} )     

I added the 2nd firewall for WSSE Api 
````
        api_wsse_secured:
            pattern: ^/api/rest/latest/(tags|activities|relation)
            # @todo: should be enabled in scope of BAP-11128
            # stateless:  true
            wsse:
                lifetime: 3600
                realm:    "Secured API"
                profile:  "Use
`````

Is this a good idea?  Did anyone have the same situation with double API authentification ?
