### ISSUE TITLE
Datagrid counts wrong records total with groupBy in select statements

### ISSUE THREAD

**Issue by mario-seidel** [orocrm/platform#64]
If I have a select statement with a join and a group by on the joined table like that:
```yaml
select:
    - o.id
    - o.title
    - sum(prod.price) as total
from:
    - { table: %order.entity.class%, alias: o }
        join:
            products:
                join: o.products
                alias: prod
        where:
            and:
                - o.status != 2
        groupBy:  prod.id
```
The class _CountQueryBuilderOptimizer_ will build a query like this:
```sql
SELECT 
  COUNT(*) 
FROM 
  (
    SELECT 
      DISTINCT o0_.id AS id0 
    FROM 
      order o0_ 
      LEFT JOIN products p1_ ON (
        o0_.products = p1_.id 
        AND p1_.business_unit_owner_id IN (198)
      ) 
    WHERE 
      o0_.status <> 2 
      AND o0_.business_unit_owner_id IN (198) 
    GROUP BY 
      p1_.id
  ) AS e
```
That gives you a wrong total count because of the DISTINCT in the select statement.
An additional verification like _$hasGroupBy_ is needed at this code line:
https://github.com/orocrm/platform/blob/master/src/Oro/Bundle/BatchBundle/ORM/QueryBuilder/CountQueryBuilderOptimizer.php#L106
