### ISSUE TITLE
PHP Warning: Illegal string offset 'value'

### ISSUE THREAD

**Issue by vodvud** [orocrm/platform#682]
Hi All!

Sometimes If I saved filters I see a warning:
`Warning: Illegal string offset 'value' in /var/www/orocrm/vendor/oro/platform/src/Oro/Bundle/DataGridBundle/Form/Handler/GridViewApiHandler.php on line 121`

https://github.com/orocrm/platform/blob/master/src/Oro/Bundle/DataGridBundle/Form/Handler/GridViewApiHandler.php#L121

There is no "**isset**" check in your code.

For example change like this one:
```php
if (isset($filter['value']) && is_array($filter['value'])) {
```

**Comment by mkudelya** [comment]
Hi @vodvud 

Thank you for pointing out the issue! Could you please tell me steps to reproduce it?

**Comment by vodvud** [comment]
Hi @mkudelya 

If I change the filter set to an existing one and update it.

for example:
**datagrid.yml, filters:**
```yaml
source:
    type: choice
    data_name: o.source
    options:
        field_options:
            choices: PeopleBundle\DBAL\Type\LeadSource::getChoices
            multiple: true
    enabled: false
agencyCommission:
    type: number
    data_name: o.agencyCommission
    enabled: false
```

If I add these and update (method PUT)

**$filters = $gridView->getFiltersData();**
returned array
```php
Array
(
    [__source] => 1
    [__agencyCommission] => 1
)
```
Where each element is not an array.

In your code, I see another place where there aren't check, I decided to offer my version of the function:
```php
    protected function fixFilters(GridView $gridView)
    {
        $filters = $gridView->getFiltersData();
        foreach ($filters as $name => $filter) {
            if (is_array($filter)) {
                if (isset($filter['type']) && $filter['type'] == null) {
                    $filters[$name]['type'] = '';
                }
                if (isset($filter['value']) && is_array($filter['value'])) {
                    foreach ($filter['value'] as $k => $value) {
                        if (isset($value['value'])) {
                            $filters[$name]['value'][$k] = $value['value'];
                        }
                    }
                }
            }
        }

        $gridView->setFiltersData($filters);
    }
```
